### ISSUE TITLE
BUG: Incompatibility with "Status Icon Counters" module

### ISSUE THREAD

**Issue by GambetTV** [jessev14/status-icon-tweaks#3]
This might be outside the purview of your module, and if so, no worries, but I love your module, but have been using the "Status Icon Counters" module for a while, which helps you keep track of how many turns are left on a status effect. Unfortunately, when used with your module, a second icon box appears next to the first, even if a counter hasn't been added. All counters will be added to this box, with no real indication as to what icon it's meant to go with. Without your module, these counters will be placed inside the actual icon box, so it's a lot easier to keep track of.

It'd be great if you could find a way for the two modules to work well together. Thanks!

![image](https://user-images.githubusercontent.com/72000497/148971576-8dba3d5e-738e-41a5-b083-10d32777ea20.png)

**Comment by jessev14** [comment]
Yeah I originally tried to make this module compatible with Status Counters, but I couldn't figure it out based on how Status Counters is programmed. I might have some ideas on what changes would need to be made to Status Counters, and I'll make a PR over there if I figure something out.

**Comment by DJ4ddi** [comment]
I made some adjustments on my end to make this possible without a major rework on your end.

One thing that we might wish to change is how the new boundary sizes are calculated: Because I need to wrap the icon and the counter into a container, Status Icon Tweaks will use the size of that container for its own calculations. This works, but isn't optimal because the container size is always slightly larger than the icon size (and I don't see a way to avoid that given PIXI's approach to boundaries).

I tried changing this in SIC, but PIXI doesn't render any child that exceeds its containers bounds (which is the reason why I originally used my own container with manual positioning instead of a local hierarchy).
The result of this problem is that icons shrink slightly when using SIT and I had to reposition the counter.

**Comment by SirAron111** [comment]
mm still seems to be a problem, just this time the icons get flattened
![Unbenannt](https://user-images.githubusercontent.com/39855956/149188294-6b29cb16-75b6-40f4-8f18-c9259221d4ea.PNG)
. Like this. It's sad, these two modules together were exactly what I was looking for.
Seems to be related to the counter scaling, since it shrinks again after putting the counter above single digits.
![Unbenannt2](https://user-images.githubusercontent.com/39855956/149189200-2670c0a5-9341-4f62-93e7-54f5c4edafb8.PNG)

**Comment by jessev14** [comment]
@DJ4ddi Thanks for making the changes! I'll take a look and see what needs to be done on my end to at least get something working. Not sure what to do about the PIXI boundary issue, but I'll keep it in mind.

**Comment by DJ4ddi** [comment]
I might need to make adjustments to provide compatibility with other modules that override effect rendering. Give me a few days to rethink my approach so you don't waste time building compatibility with a method that gets replaced a day later.

**Comment by DJ4ddi** [comment]
I believe to have found a way to run SIC counter positioning reliably after other modules that change effect rendering (without overriding the rendering itself). I tested this with SIT in various configurations and found no further issues, so this ticket can be closed.

**Comment by GambetTV** [comment]
This is working great on my end. Thank you, to both of you! These modules are meant for each other!

**Comment by SirAron111** [comment]
works great GJ
